name: Content Validator

on:
  # Run on PRs to catch missing required fields before merge
  pull_request:
    paths:
      - 'content/notes/**/*.md'

  # Run on push to master to validate all notes
  push:
    branches:
      - master
    paths:
      - 'content/notes/**/*.md'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run content validator
        run: .github/scripts/validate-seo.sh

      - name: Comment on PR with results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Content validation failed. Please check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.\n\nCommon issues:\n- Missing `title` field\n- Missing `date` field'
            })
